### ISSUE TITLE
Orphan? entries in Localities.json

### ISSUE THREAD

**Issue by dreaded369** [SimonCropp/AustralianElectorates#507]
These may have some historical significance I'm unaware of, but I noticed about 56 entries in Localities.json which which don't have an Electorate.
eg.
 {
    "Place": "Harcrest",
    "Postcode": 3152,
    "Electorate": ""
  },
  {
    "Place": "Knox",
    "Postcode": 3152,
    "Electorate": ""
  },

**Comment by SimonCropp** [comment]
sorry for the much delayed response. this is now fixed
